# Default values for package-booking-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
configServer: config-server-service.b2b2c-services.svc.cluster.local
region: kubernetes-eu-wes1
zone: kubernetes-eu-wes-1a
provider: kubernetes-env

image:
  repository: live-package-booking-api
  tag: 1.26-492
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30100


ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: "mycluster.package-booking-api:30002"
      paths: 
        - /
     

